name: Check Status of Pods

on: workflow_dispatch

jobs:
  check-pods:
    runs-on: ubuntu-latest
    steps:
    - name: Connect to K3s host
      run: |
        mkdir ~/.ssh
        echo "OK mkdir ~/.ssh"
        eval `ssh-agent -s`
        echo "OK ssh-agent -s"
        ssh-add - <<< "${{ secrets.SSH_KEY }}"
        echo "OK ssh add"
        ssh-keyscan -p 32510 178.124.206.53 >> ~/.ssh/known_hosts
        echo "ssh keyscan"
        ssh jump_sa@178.124.206.53 -p 32510 ssh-keyscan 192.168.208.7 >> ~/.ssh/known_hosts
        echo "ssh"
        ssh -o ProxyCommand="ssh -W %h:%p jump_sa@178.124.206.53 -p 32510 " root@192.168.208.7 "kubectl get pods -A" >> output.log

    - name: Check Crash pods
      id: check-pods
      run: |
        echo "$(cat  output-pods.log | grep -v Running)" >> crash_report 2>&1
        echo "pods-dont-work=$(cat output-pods.log | grep -v 'Running\|Completed ' | wc -l)" >> $GITHUB_OUTPUT
