name: Check Status of Pods

on: workflow_dispatch

jobs:
  check-pods:
    runs-on: ubuntu-latest
    steps:
    - name: Connect to K3s host
      run: |
        mkdir ~/.ssh
        echo "OK mkdir ~/.ssh"
        eval `ssh-agent -s`
        echo "OK ssh-agent -s"
        ssh-add - <<< "${{ secrets.SSH_KEY }}"
        echo "OK ssh add"
        ssh-keyscan -p 32510 ${{ secrets.JUMP_HOST }} >> ~/.ssh/known_hosts
        echo "ssh keyscan"
        ssh ${{ secrets.JUMP_USERNAME }}@${{ secrets.JUMP_HOST }} -p 32510 ssh-keyscan ${{ secrets.HOST_USER_K8S_1 }} >> ~/.ssh/known_hosts
        echo "ssh"
        ssh -o ProxyCommand="ssh -W %h:%p ${{ secrets.JUMP_USERNAME }}@${{ secrets.JUMP_HOST }} -p 32510 " ${{ secrets.HOST_USER_K8S_1 }}@${{ secrets.HOST_K8S_1 }} "kubectl get pods -A" >> output.log

    - name: Check Crash pods
      id: check-pods
      run: |
        echo "$(cat  output-pods.log | grep -v Running)" >> crash_report 2>&1
        echo "pods-dont-work=$(cat output-pods.log | grep -v 'Running\|Completed ' | wc -l)" >> $GITHUB_OUTPUT
