name: Check Status of Pods

on: workflow_dispatch

jobs:
  check-pods:
    runs-on: ubuntu-latest
    steps:
    - name: Check SSH_PKEY Secret
      run: |
        echo "Secret SSH_PKEY: ${{ secrets.SSH_KEY }}"
        echo "${{ secrets.SSH_KEY }}" > secret.key.pem
        chmod 600 secret.key.pem
        ssh-keygen -l -f secret.key.pem
      continue-on-error: true

    - name: Connect to K8s master host
      run: |
        mkdir ~/.ssh
        echo "OK mkdir ~/.ssh"
        eval `ssh-agent -s`
        ssh-add - <<< "${{ secrets.SSH_KEY }}"
        ssh-keyscan -p 32510 ${{ secrets.JUMP_HOST }} >> ~/.ssh/known_hosts
        ssh ${{ secrets.JUMP_USERNAME }}@${{ secrets.JUMP_HOST }} -p 32510 ssh-keyscan ${{ secrets.HOST_K8S_1 }} >> ~/.ssh/known_hosts
        ssh -o ProxyCommand="ssh -W %h:%p ${{ secrets.JUMP_USERNAME }}@${{ secrets.JUMP_HOST }} -p 32510" ${{ secrets.HOST_USER_K8S_1 }}@${{ secrets.HOST_K8S_1 }} "kubectl get pods -A" >> output.log

    - name: Check Crash pods k8s1
      id: check-pods-k8s1
      run: |
        echo "$(cat output_k8s1.log)" >> crash_report 2>&1
        echo "pods-dont-work=$(cat output_k8s1.log | grep -v 'Running\|Completed' | wc -l)" >> $GITHUB_OUTPUT

    - name: Upload Crashed Pods List
      if: steps.check-pods-k8s1.outputs.pods-dont-work != 1
      uses: actions/upload-artifact@v4
      with:
        name: Dead pods
        path: output_k8s1.log

    - name: Connect to K8s host
      run: |
        ssh ${{ secrets.JUMP_USERNAME }}@${{ secrets.JUMP_HOST }} -p 32510 ssh-keyscan ${{ secrets.HOST_K8S_2 }} >> ~/.ssh/known_hosts
        ssh -o ProxyCommand="ssh -W %h:%p ${{ secrets.JUMP_USERNAME }}@${{ secrets.JUMP_HOST }} -p 32510" ${{ secrets.HOST_USER_K8S_2 }}@${{ secrets.HOST_K8S_2 }} "kubectl get pods -A" >> output_k8s2.log

    - name: Check Crash pods k8s2
      id: check-pods-k8s2
      run: |
        echo "$(cat output_k8s2.log)" >> crash_report 2>&1
        echo "pods-dont-work=$(cat output_k8s2.log | grep -v 'Running\|Completed' | wc -l)" >> $GITHUB_OUTPUT

